name: Ping
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "welcome to sai 127.0.0.1"
      - name: file create
        run: touch sai.txt
      - name: list
        run: ls
        

    
